### ISSUE TITLE
Swipeable doesn't work on desktop browsers (without touch)

### ISSUE THREAD

**Issue by Sandstedt** [leandrowd/react-responsive-carousel#521] opened 2020-10-28 09:12 UTC
(Probably a duplicate of #374)

THe provided example: [link](http://react-responsive-carousel.js.org/storybook/?path=/story/01-basic--base) with props `swipeable` and `emulateTouch` set to true, doesn't work in desktop browsers with a mouse as input device (havn't tried using a touchscreen desktop). You can drag, but I guess that the [hasMoved ](https://github.com/leandrowd/react-responsive-carousel/blob/a2738b6931be48ab078661813d4c7979929da57c/src/components/Carousel.tsx#L501) doesn't calculate the values correct. Your can drag from first slide 1 to slide -1 (or the last slide / backwards), but not from slide 1 to 2. It just snaps right back without changing slide.

To be even more complex in the error. Sometimes it does work. Especially in Chrome/Edge. In Firefox almost never. So maybe is just a default threshold value that needs to be changes. Tried changing the `swipeScrollTolerance`, but didn't notice any differences.

Tested on Windows 10, Firefox 82 (latest), Edge / Chrome 86.

**Comment by Sandstedt** [comment] 2020-10-28 09:15
(Maybe solved by [PR 509](https://github.com/leandrowd/react-responsive-carousel/pull/509), havn't been able to verify yet)

**Comment by blainegarrett** [comment] 2020-12-04 19:56
Unsure if this is your exact issue, but I wanted to get the Mac Touchpad swiping working. I had to do something like this:

```
  const scrollTimeoutRef = React.useRef(null);
  const carouselRef = React.useRef<Carousel>(null);

  const handleScroll = (e) => {
    // Cancel previous scroll events
    if (scrollTimeoutRef.current) {
      clearTimeout(scrollTimeoutRef.current);
    }

    scrollTimeoutRef.current = setTimeout(() => {
      const yDir = e.deltaY;
      const xDir = e.deltaX;

      if (yDir > 0 || xDir > 0) {
        carouselRef.current.increment();
      } else if (yDir < 0 || xDir < 0) {
        carouselRef.current.decrement();
      }
    }, 75);
  };

  useEffect(() => {
     // Add the event listener 
      window.addEventListener('wheel', handleScroll, true);
      return window.removeEventListener('wheel', handleScroll);
}, []);

    return (<Carousel ref={carouselRef}>...</Carousel>);
```
Unsure if this is the best solution. Storing the timeout in a ref vs state is something I have not done before. 
I'd be great if this was built in to the swipe behavior of the component. 

Tested on Safari 14.0.1, Chrome 87.0, FF 81.0 + same browsers on ios and android.

**Comment by Sandstedt** [comment] 2020-12-14 22:21
No this is only about the simulate touch capabilities. Like the simulated touch work in your browsers responsive dev tool. So you can click, hold and then drag the area to move it, or in this case, swipe it when you release with a certain move distance and (perhaps) velocity.

But thanks anyway 😊.

Will try to make some time to investigate more into this.

**Comment by naveennsit** [comment] 2020-12-17 11:47
@Sandstedt did you get any soulution ?? I have facing same issue.I checked PR also but it is not working.

**Comment by Mf-ff99** [comment] 2020-12-31 02:41
Same here, this would be a nice feature.

**Comment by Sandstedt** [comment] 2020-12-31 16:59
@naveennsit Nope sorry, haven't got to it yet.

**Comment by renancleyson-dev** [comment] 2021-02-05 19:53
Probably a duplicate of #517 too.

**Closed** 2021-08-11 21:35 UTC
Labels: wontfix
