### ISSUE TITLE
how to create custom next and prev button in react-responsive-carousel i am having this issus

### ISSUE THREAD

**Issue by muhammadsarim555** [leandrowd/react-responsive-carousel#278] opened 2018-11-04 14:49 UTC

**Comment by sezna** [comment] 2018-11-08 18:55
I do not believe this is currently a feature. You can add it and submit a PR if you want it.

**Comment by sezna** [comment] 2018-11-08 18:59
This is a duplicate of #232

**Comment by leandrowd** [comment] 2018-12-20 09:49
You can implement your own controls... Check this example: https://github.com/leandrowd/react-responsive-carousel/blob/master/stories/index.js#L59

**Comment by sudokzt** [comment] 2019-11-14 08:43
@leandrowd  Thank you for good idea!

**Closed** 2020-04-05 10:07 UTC
