### ISSUE TITLE
React Responsive Carousels not showing when deployed on Netlify

### ISSUE THREAD

**Issue by BPopek** [leandrowd/react-responsive-carousel#388] opened 2019-12-22 18:37 UTC
Hello, I am having an issue with my deployed website not showing a few different react responsive image carousels. These all work just fine when viewed locally, but nothing is showing and they are blank on my deployed Netlify website. I have checked and all images are uploaded on Github, and I have tried troubleshooting on Netlify but have not had any success in figuring out the issue. The galleries vary in size from having only 2 to 6-7 photos but none are showing properly. Deployed site is www.betsypopek.com in case viewing the website itself might help with troubleshooting. 

The repository for my portfolio is here: https://github.com/BPopek/bp-portfolio. Issues are on all Graphic Design pages as well as my UX project page.

Any help would be appreciated!

**Comment by marko-ignjatovic** [comment] 2020-03-25 13:27
Hi @BPopek, I actually checked your portfolio website and it seems that you fixed it somehow? Anyway, have you also tried to optimize all of your assets which are used by `react-responsive-carousel` ? (It will load images much faster)

**Comment by sam-cross** [comment] 2020-04-24 18:44
Possible duplicate of #392?

**Closed** 2021-07-09 06:28 UTC
Labels: wontfix
