### ISSUE TITLE
Changing carousel image size

### ISSUE THREAD

**Issue by Jordanh1996** [leandrowd/react-responsive-carousel#250] opened 2018-06-07 15:05 UTC
Hi,
I am in a scenario where I have a lot of images to put in the carousel, now the images size(height x width) varies. And the carousel height is fixed to the largest image size. I would not like that since some are huge, what I want is to specify a fixed height for the carousel image. And I can't seem to achieve that because not only the library doesn't offer any way to specify an height. The image element of the carousel itself doesn't have any className that I can overwrite. The only fix I found is to change all of the img tags in the page, but now other images are affected by that.
Please help me.
one solution I thought of is to add a className to that image tag in the source code( I know its not recommended) but I am to newbie to do that.
THANKS

**Comment by havgry** [comment] 2018-08-07 08:59
I think this is related to #197. Currently, varying slide widths aren't supported.

**Comment by sezna** [comment] 2019-10-18 21:42
The above comment is correct. I'm closing this as a duplicate of #197. As stated in that issue, PRs are welcome.

**Closed by sezna** 2019-10-18 21:42 UTC
