### ISSUE TITLE
i keep getting this issue

### ISSUE THREAD

**Issue by Tenoywil** [leandrowd/react-responsive-carousel#470] opened 2020-07-02 13:00 UTC
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: Thumbs

**Comment by k0o** [comment] 2020-07-21 18:52
Me too, have you found a solution?

**Comment by k0o** [comment] 2020-07-21 18:54
up!

**Comment by jleider** [comment] 2020-09-28 14:26
This is a duplicate of #454

**Closed** 2021-07-09 05:42 UTC
Labels: wontfix
