### ISSUE TITLE
On swipe - onChange triggered twice

### ISSUE THREAD

**Issue by Merynek** [leandrowd/react-responsive-carousel#562] opened 2021-02-16 13:26 UTC
Here is example from your repo (storybook):
![example2](https://user-images.githubusercontent.com/6883795/108068790-d6560680-7062-11eb-83b8-2bf0ea796b9f.gif)

**Comment by renancleyson-dev** [comment] 2021-02-18 03:54
I couldn't reproduce your issue, it's not changing the slide twice for me. Feel free to provide an example by forking [this sandbox](https://codesandbox.io/s/react-responsive-carousel-qq29g) or provide steps to reproduce the bug.

**Comment by dnish** [comment] 2021-02-23 07:40
I got the same problem, there are some "ghost swipes" even when I'm not changing the swipes. You have to swipe manually, it happens from time to time. Also got this issue on our production app

**Comment by Merynek** [comment] 2021-02-23 08:39
This example (gif) is storybook in this repo. Just set autoplace = false and try swipe by mouse.

**Comment by dnish** [comment] 2021-02-23 08:41
@Merynek Check if downgrading to version 3.2.11 fixes the problem on your side, too. I guess one of the merged PRs is causing the issue.

**Comment by Merynek** [comment] 2021-02-23 08:52
> @Merynek Please check if downgrading to version 3.2.11 fixes the problem on your side, too. I guess one of the merged PRs is causing the issue.

Nice, it solved my problem. :-)

**Comment by renancleyson-dev** [comment] 2021-02-25 02:45
> This example (gif) is storybook in this repo. Just set autoplace = false and try swipe by mouse.

I think that you used the storybook locally while I tried to reproduce it on a website with the storybook of the repo, but I don't know if the library is updated on the website. When I reproduced it locally on v3.2.12, it auto-played once, as you said.

Probably PR #511 is causing it by removing some checks that verify if autoplay is `true` to swipe.

**Comment by McRight** [comment] 2021-02-26 15:00
Can confirm that PR #511 is causing the issue with autoplay being triggered once.

![autoPlay bug](https://user-images.githubusercontent.com/32580511/109316022-d79de500-7853-11eb-9590-bd4a032c2e01.gif)

If I add back the checks for autoPlay the bug is gone.

**Closed** 2021-04-01 00:59 UTC
