### ISSUE TITLE
Slides wrapped in a React.Fragment displaying the Fragment as a single slide

### ISSUE THREAD

**Issue by npasqua** [leandrowd/react-responsive-carousel#279] opened 2018-11-06 17:29 UTC
I have a pretty simple use case and am wondering if there is any support for it planned or currently available. We've got a single carousel component that can have different sets of slides. We don't want to continually unmount/mount the Carousel component for each set of slides, just update the props on the Carousel component dependent on the new set of slides. We want to be able to do the following:

Carousel Container:
```
class CarouselContainer extends React.PureComponent<props, state> {
...

    getSlides = (index: number) => {
        switch (index) {
            case 1:
                return <MySlides1 />;
            case 2:
                return <MySlides2 />;
            default:
                return;
        }
    }

    render() {
        return (
           <Carousel {...this.state.carouselProps}>
              {this.getSlides(this.state.currentIndex)}
           </Carousel>
        );
    }
}
```

MySlides1
```
class MySlides1 extends React.PureComponent<props, state> {
...
    render() {
        return (
           <React.Fragment>
               <FirstSlideInMySlides1/>
               <FirstSlideInMySlides2/>
           </React.Fragment>
        );
    }
}
```

I would expect that the children of the Fragment should be depicted as the slides in the Carousel - as it stands with this example the Carousel will use the Fragment as a singular slide and both `FirstSlideInMySlides1` and `FirstSlideInMySlides2` will be on the same slide.

**Comment by sezna** [comment] 2018-11-08 18:46
I believe this is expected behavior. A React ‘Fragment’ essentially groups things together until they hit the DOM, then it removes itself. When you are passing children into the carousel, the carousel sees a ‘Fragment’ child. Anything within a fragment is treated as a singular component until it is actually rendered, and then the fragment is removed. 

If the carousel were to check if a child was a ‘Fragment’ and individually render its children, it would ruin the use cases where people are using ‘Fragment’s to group together stuff specifically so it will be rendered as one component (the intended use case).

**Comment by quadlayers** [comment] 2020-05-12 23:05
Hello

I have the same issue

Is there any fix for this?

**Comment by leandrowd** [comment] 2020-05-13 00:15
Each direct child of the carousel will be a slide, this is expected.

**Comment by quadlayers** [comment] 2020-05-13 15:13
hello @leandrowd 
i understand that is the expected behavour
but im trygin to implement slick slider via filter, and i cant get the list of childs without fragment node

1. ive tried flattenChildren, but this dont work becase Block is the entire component
2. i've tried to create a ref on childs to use the property slide but it dosent work

`const addBlockLayout = createHigherOrderComponent((Block) => {
    return enhance(({ select, ...props }) => {

        const {
            parentProps,
            latestPosts
        } = props;

        if (parentProps && parentProps.name == 'test/slider' && latestPosts) {

            //console.log(Block);

            return [
                <Slider {...parentProps}>
                    <Block {...props} />
                </Slider>
            ];
        }

        return [
            <Block {...props} />
        ];

    });
}, 'addBlockLayout');
addFilter('test.BlockEditLayout', 'test/block/slider/layout', addBlockLayout);
`

**Comment by leandrowd** [comment] 2020-05-13 20:10
Not sure why you have the fragment around your element but you should be able to return an array instead... try changing the notation of your result.

**Closed** 2021-07-09 06:28 UTC
Labels: wontfix
